controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_user_edit_profile:
    path: /user/edit-profile
    controller: App\Controller\UserController::editProfile
    methods: [GET, POST]
